### ISSUE TITLE
Brew package installs python

### ISSUE THREAD

**Issue by epec254** [yasyf/summ#5]
Hey folks - your brew package installs brew's version of `python`.  This - at least in my case - messed up my `pyenv` based python management on OS X because I do not want python installed via brew - it is managed via pyenv.  Not sure if there is an easy fix here, but wanted at least call out.

**Comment by yasyf** [comment]
@epec254 ya that's super annoying.. I think the best way to handle that for now is to use `pip install summ`. I'll update the readme to reflect this.
