### ISSUE TITLE
Error installing yasyf/summ/redis-stack

### ISSUE THREAD

**Issue by heijligers** [yasyf/summ#6]
I'm trying to follow the instructions. Freshly installed redis and redis-stack.

Getting the following error on a apple m1 mac.

brew services start yasyf/summ/redis-stack
==> Tapping homebrew/services
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 2391, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 2391 (delta 17), reused 23 (delta 9), pack-reused 2349
Receiving objects: 100% (2391/2391), 661.82 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (1081/1081), done.
Tapped 1 command (45 files, 828.9KB).
Could not enable service: 125: Domain does not support specified action
Error: Failure while executing; `/bin/launchctl enable gui/505/homebrew.mxcl.redis-stack` exited with 125.

**Comment by yasyf** [comment]
hey @heijligers, haven't seen this before but there's a blog post [here](https://www.boesen.me/posts/fixing-domain-does-not-support-specified-action-when-running-redis-on-macos-12-1-2022/) that might be helpful

**Comment by heijligers** [comment]
Awesome! thanks... I indeed use a multiuser brew installation according the "official" method of using a separate "brewuser". That meant the brew uid was different from my own uid. Manually starting the redis stack worked! thanks for the tip.

**Comment by yasyf** [comment]
awesome! heads up that the current release is broken, I'm pushing out a fix shortly
